### ISSUE TITLE
crc bits

### ISSUE THREAD

**Issue by iceman1001** [madler/crcany#1]
Hello Mr Adler,
Since I didn't find a email I made this issue to ask a question. 

I've an issue with making a general crc bitwise imp,  so when I found yours here I thought I would manage to get your stuff into the one I'm trying at.  https://github.com/iceman1001/proxmark3/blob/master/common/crc.c
However,  crc is black magic,  woodo, to me.  What am I not getting?  When I try to use it with a crc4 setting, and there is 12bits it just fails.  Would you mind having a look at it?

**Comment by madler** [comment]
I have no idea what you mean by "and there is 12bits".

**Comment by iceman1001** [comment]
Allow me to show the setup.  http://pastebin.com/dX7xqjbH

I tried to make it general and compliant with Ross Williams' Rocksoft™ model of parametrised CRC algorithms.  However I must missunderstood something. Since it doesn't work for me. I saw that crcany is compliant Ross Wiliams's model and can be call a crc4 with message of n bits where n is larger than 4.

**Comment by madler** [comment]
This does not appear to be a crcany development question, so you should move this discussion to stackoverflow.
