### ISSUE TITLE
Seg fault in read_model

### ISSUE THREAD

**Issue by Silicomancer** [madler/crcany#2]
I tried to test your code. I created a C project, added the modules crc and model, added a small main() like this and let it run:

```
#include <stdio.h>

#include "crc.h"

int main(int argc, char *argv[])
{
   printf("Hello World!\n");

   char* str = "width=16 poly=0x1021 init=0x0000 refin=true refout=true xorout=0x0000 check=0x2189 name=\"KERMIT\"";

   model_t model;
   int rr = read_model(&model, str);

   crc_table_bytewise(&model);

   char* data = "123456789";
   word_t crc = crc_bytewise(&model, model.init, data, 9);

   return 0;
}
```

Should this work? I get a segmentation fault in line 45 of model.c in read_model().

**Comment by madler** [comment]
`read_model()` needs to be able to modify the string, so it can't be a literal. You can use `strdup()` to copy the string to allocated memory.

**Comment by Silicomancer** [comment]
Oh, I see. Sorry, I should have understood this. However an input parameter that is modified is uncommon, isn't it?

**Comment by Silicomancer** [comment]
I updated the code:

```
#include <stdio.h>
#include <string.h>
#include <assert.h>
#include <stdlib.h>

#include "crc.h"

int main()
{
   printf("Hello World!\n");

   const char* str = "width=8 poly=0x39 init=0x00 refin=true refout=true xorout=0x00 check=0x15 name=\"CRC-8/DARC\"";

   model_t model;
   char* str2 = strdup(str);
   int rr = read_model(&model, str2);
   free(str2);
   assert(rr==0);

   crc_table_bytewise(&model);

   const char* data = "123456789";
   word_t crc = crc_bytewise(&model, model.init, data, 9);
   printf("crc = 0x%lx, check = 0x%lx\n", crc, model.check);

   return 0;
}
```
Seems I am still doing something wrong since it outputs "crc = 0x70, check = 0x15"... i.e. actual value and expect value are different. I confirmed the check value using an online tool and 0x15 should be correct.

**Comment by madler** [comment]
Please re-read my comment above.

Yes, the `*buf`'s should be const. I have pushed a commit to fix that.

**Comment by madler** [comment]
In response to your question about modifying an input parameter, another example is the library function `strtok()`, which modifies its input string, performing a function much like `read_model()`.
