### ISSUE TITLE
Can this generate 96 bit CRC checksums for contents of a file?

### ISSUE THREAD

**Issue by Arefu** [madler/crcany#4]
Title sums it, but I'm not entirely sure if this is what I need to do it.

**Comment by madler** [comment]
Yes, if you have a 96-bit CRC definition. However I've never seen a 96-bit CRC polynomial.

**Comment by Arefu** [comment]
Well since I have no knowledge of this stuff, that is gibberish to me. 

From Googling quickly if by "polynomial" you mean a file I want to generate it from yep I have one of those. (Probably doesn't mean this)

I'm not a math programmer so I don't understand encryption in the slightest.

**Comment by madler** [comment]
CRC's are not encryption. You are likely confused about what you're looking for.

**Comment by Arefu** [comment]
Validation of data? Consistency checking to make sure the data isn't corrupt in any way? Something like that? Basically a hash right? If that's all yes (or some of it) then it is what I'm looking for, but can't find a way to generate one that's 96bits/bytes long

**Comment by madler** [comment]
Why 96 bits? (You do know that 96 bytes is not the same thing, right?)

**Comment by Arefu** [comment]
It's what this program uses for validation. Not my choice sadly.

Also, I didn't know what one CRC uses (Like I said, I do don't this stuff)

**Comment by madler** [comment]
I'm about to give up on trying to help you. You are not providing any information. What is the "this program" are you talking about? What are you reading? What does it actually say? What are you trying to do? I recommend that you post your actual question, with information, on stackoverflow.com. This github repository is not the place for this.
