### ISSUE TITLE
the comments about ref and rev is incorrect based on the actual code in read_model()

### ISSUE THREAD

**Issue by larixsoft** [madler/crcany#5]
The  following comments about ref and rev in model.h is not correct.
"ref and rev are derived from refin and refout.  ref and rev must be 0 or 1.
   ref is the same as refin.  rev is true only if refin and refout are
   different.  rev true is very uncommon, and occurs in only one of the 72 CRCs
   in the RevEng catalogue.  When rev is false, the common case, ref true means
   that both the input and output are reflected. Reflected CRCs are quite
   common."

According to read_model(), model->ref is the same as "refin" and model->rev is the same as "refout".

**Comment by madler** [comment]
No, because `process_model()` needs to be called after `read_model()`. `process_model()` does this: `model->rev ^= model->ref;`.
