### ISSUE TITLE
Generated code does not match documented behavior for mem==NULL

### ISSUE THREAD

**Issue by tomlogic** [madler/crcany#7]
The header file from `crcgen` includes this documentation in the comments:

> If mem is NULL, then the other arguments are ignored, and the initial CRC, i.e. the CRC of zero bytes, is returned.

But the generated code always returns 0.  Do you want a pull request for updated `crcgen.c` to return the `crc` parameter instead?  Should there be test code to verify that a `NULL` data pointer returns the starting CRC?

**Comment by madler** [comment]
It does in fact return the initial CRC, which is not zero for all CRC definitions. I do not understand what you are trying to report.

**Comment by tomlogic** [comment]
From the generated `crc16buypass.c`.  I think all of these `return 0;` statements should be `return crc;`.

```
unsigned crc16buypass_bit(unsigned crc, void const *mem, size_t len) {
    unsigned char const *data = mem;
    if (data == NULL)
        return 0;
...

unsigned crc16buypass_byte(unsigned crc, void const *mem, size_t len) {
    unsigned char const *data = mem;
    if (data == NULL)
        return 0;
...

unsigned crc16buypass_word(unsigned crc, void const *mem, size_t len) {
    unsigned char const *data = mem;
    if (data == NULL)
        return 0;
...
```

**Comment by madler** [comment]
You are not understanding the purpose of the value returned when `mem` is `NULL`. That is the initial value of the CRC for that particular CRC definition. The initial value is the CRC of an empty, zero-byte message. It is a constant.

That constant is not always zero. See for example crc16modbus.c, where the constant is `0xffff`.

**Comment by tomlogic** [comment]
Ah!  Now I understand.  And a caller can use that return value as the seed for calculating a CRC on multiple chunks of data.

```
crc = crc16variant_byte(0, NULL, 0);
while ((read = read_data(buffer, sizeof(buffer))) > 0) {
    crc = crc16variant(crc, buffer, read);
}
```

**Comment by madler** [comment]
Correct. Though you need that value even if you are doing just one chunk.
